name: chuanmapo_flutter
version: 1.0.0+1
publish_to: none
description: Chuan Ma Po Restaurant.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  path_provider: ^2.1.2
  flutter_easyloading: 3.0.5
  flutter_svg: 2.0.9
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  dio: 5.4.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  esc_pos_utils_plus: 2.0.3
  screenshot: ^3.0.0
  intl: ^0.19.0
  # share: ^2.0.4

  flutter: 
    sdk: flutter
  collection: ^1.18.0
  flutter_pos_printer_platform_image_3_sdt: ^1.2.12
  package_info_plus: ^8.1.1


dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - assets/fonts/
    - assets/svg/

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icons/icon.png
  web: 
    image_path: assets/icons/icon.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/icons/icon.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/icons/icon.png
    generate: true
  ios: true
  min_sdk_android: 23

