<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ExchangeRate extends Model
{
    use HasFactory,SoftDeletes;

    protected $table = 'exchange_rates';
    protected $fillable = [
        'exchange_date',
        'exchange_year',
        'exchange_month',
        'exchange_year_month',
        'exchange_days',
        'rate_standard',
        'rate_returned',
        'rate_nssf',
        'rate_taxation',
        'deleted_at',
        'created_at',
        'updated_at',
    ];
    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    protected $casts = [
        'is_enable' => 'boolean'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($exchange_rate) {
            $exDate = Carbon::parse($exchange_rate->exchange_date);
            $exchange_rate->exchange_year=$exDate->year;
            $exchange_rate->exchange_month=$exDate->month;
            $exchange_rate->exchange_days=$exDate->format('d');;
            $exchange_rate->exchange_year_month=$exDate->format('Y-m');

        });

    }
}
