<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleDetail extends Model
{
    use HasFactory;

    protected $table = 'sale_details';

    protected $fillable = [
        'sale_table_id',
        'description',
        'remark',
        'qty',
        'food_price',
        'total_amount',
        'discount_percentage',
        'discount_amount',
        'total_amount_after_discount',
        'food_dish_json',
        'food_dish_detail_json',
        'food_dish_id',
        'food_dish_detail_id',
        'created_at',
        'updated_at',
    ];
    protected $hidden = [
        'created_at',
        'updated_at',
    ];
    protected $casts = [
        'qty' => 'float',
        'discount_percentage' => 'float',
        'discount_amount' => 'float',
        'total_amount' => 'float',
        'total_amount_after_discount' => 'float',
    ];

    public function sale_table()
    {
        return $this->belongsTo(SaleTable::class);
    }

    protected static function booted()
    {
        self::creating(function ($model) {
            $model->total_amount = $model->qty * $model->food_price;
            $model->discount_amount = $model->total_amount * $model->discount_percentage / 100;
            $model->total_amount_after_discount = $model->total_amount - $model->discount_amount;
        });

        self::updating(function ($model) {
            $model->total_amount = $model->qty * $model->food_price;
            $model->discount_amount = $model->total_amount * $model->discount_percentage / 100;
            $model->total_amount_after_discount = $model->total_amount - $model->discount_amount;
        });
        self::created(function ($model) {
            $saleTable = SaleTable::find($model->sale_table_id);
            //=========================ALREADY UPDATE FUNCTION IN SALE TABLE MODEL=========================

            $totalAmountSaleDetail = $saleTable->sale_detail()->sum('total_amount_after_discount');
            $saleTable->total_amount = $totalAmountSaleDetail;
            $saleTable->save();
        });

        self::updated(function ($model) {
            $saleTable = SaleTable::find($model->sale_table_id);
            //=========================ALREADY UPDATE FUNCTION IN SALE TABLE MODEL=========================

            $totalAmountSaleDetail = $saleTable->sale_detail()->sum('total_amount_after_discount');
            $saleTable->total_amount = $totalAmountSaleDetail;
            $saleTable->save();
        });
        self::deleted(function ($model) {
            $saleTable = SaleTable::find($model->sale_table_id);
            //=========================ALREADY UPDATE FUNCTION IN SALE TABLE MODEL=========================

            $totalAmountSaleDetail = $saleTable->sale_detail()->sum('total_amount_after_discount');
            $saleTable->total_amount = $totalAmountSaleDetail;
            $saleTable->save();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function foodDish()
    {
        return $this->belongsTo(FoodDish::class);
    }
    public function foodDishDetail()
    {
        return $this->belongsTo(FoodDishDetail::class);
    }
}
